server:
  context-path: /testM
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false&allowMultiQueries=true
    userName: root
    passWord: root
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 10000
      minIdle: 0
      maxIdle: 10
      max-active: 20
      test-on-borrow: true
      test-while-idle: true
      validation-query: select 1
  redis:
    host: 192.168.96.232
    port: 6379
    password: vs959yUyx3
    database: 0
    pool:
      max-active: 20
      max-idle: 20
      min-idle: 0
  rabbitmq:
    host: 192.168.96.232
    port: 5672
    username: rabbituser
    password: X81xoNuhNt
    virtual-host: /vhepro-dev
    cache:
      connection:
        mode: channel
      channel:
        size: 20
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
    publisher-returns: true
    publisher-confirms: true

  
jwt:
  header: Authorization
  secret: viewhigh
  expiration: 7200
  auth:
    path: /auth
  validate:
    path: /api

login:
  validateInitialPwd: true
  pwd: 14141414


mybatis:
  mapper-locations: 
    classpath:mapper/*.xml
#  type-aliases-package: 
#    com.viewhigh.epro.svc.dmcc.domain
  configuration:
    cache-enabled: true
    
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

orika:
  # Whether to enable auto-configuration.
  # Defaults to true.
  enabled: true
  # Whether to use built-in converters (MapperFactoryBuilder#useBuiltinConverters(boolean)).
  # Follows Orika's behavior by default.
  useBuiltinConverters: true
  # Whether to use auto-mapping (MapperFactoryBuilder#useAutoMapping(boolean)).
  # Follows Orika's behavior by default.
  useAutoMapping: true
  # Whether to map null values (MapperFactoryBuilder#mapNulls(boolean)).
  # Follows Orika's behavior by default.
  mapNulls: false
  # Whether to dump the current state of the mapping infrastructure objects
  # upon occurrence of an exception while mapping (MapperFactoryBuilder#dumpStateOnException(boolean)).
  # Follows Orika's behavior by default.
  dumpStateOnException: false
  # Whether the class-map should be considered 'abstract' (MapperFactoryBuilder#favorExtension(boolean)).
  # Follows Orika's behavior by default.
  favorExtension: false
  # Whether full field context should be captured (MapperFactoryBuilder#captureFieldContext(boolean)).
  # Follows Orika's behavior by default.
  captureFieldContext: false